services:
  - type: web
    name: litlist-backend
    runtime: python
    plan: free
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:8080 run:app
    envVars:
      - key: PYTHONPATH
        value: .
    rootDir: backend/src
    autoDeploy: true